### ISSUE TITLE
Can't compile on Nano 33 BLE

### ISSUE THREAD

**Issue by pierre-b** [brunocalou/Timer#4] opened 2019-12-24 15:36 UTC
Hi,
I get the following error while compiling for a Nano 33:
`Blink:12:1: error: 'Timer' does not name a type; did you mean 'time'?
 Timer timer;`

The lib is under Arduino/libraries/Timer

Any suggestion please?
Thanks

**Comment by brunocalou** [comment] 2019-12-26 17:57
Hello,

It looks like the compiler couldn't find the timer.h file

If you are using Arduino IDE, have you closed it after placing the library in Arduino/libraries?

**Comment by pierre-b** [comment] 2019-12-27 16:34
The issue should come from the compatibility with the Nano 33, as it does compile for Uno.

Maybe the Timer lib uses functions that are not available for SAMD21?!

**Comment by brunocalou** [comment] 2019-12-27 21:07
I have installed the latest Nano 33 dependency and it compiled fine... Am I doing it right? Are these the correct board and programmer configs?

<img width="892" alt="Screen Shot 2019-12-27 at 18 04 33" src="https://user-images.githubusercontent.com/5948318/71532700-6d965280-28d3-11ea-939f-b8cfd77dfedb.png">

**Comment by pierre-b** [comment] 2019-12-28 09:30
My bad it doesn't work on the Arduino Nano 33 BLE, which is another variant.

**Comment by brunocalou** [comment] 2019-12-30 12:53
I could reproduce the same problem on Arduino Nano 33 BLE, but it is not a due to the library

I tried to compile the examples that come with the Arduino IDE and include a library but none of them compiled. So it's probably a problem with the setup or the compiler

**Closed as completed** 2020-10-09 14:06 UTC
